on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Cloudflare Workers
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@v3.14.1
